using System.Text.Json;
using iBarter.Routing;
using Xunit;

namespace AutomaticRoutePlanningTests;

/// <summary>
/// Audit round 8: extra tests pinning the migration + restore
/// contracts that the WPF-coupled code paths already enforce:
///   * every saved BarterStep must map to a current task;
///   * Item1/Item2/quantity changes are refused;
///   * deleted RowIds are refused;
///   * ambiguous matches are rejected;
///   * the migrated plan carries the new request's fingerprint;
///   * SelectedBarterRowId is migrated through the same map;
///   * Barter.PlannerRowId is preserved by the clone path and
///     regenerated by the audit-only RegeneratePlannerRowId path;
///   * the map handler resolves the target by persistent
///     PlannerRowId, not by re-deriving the row.
/// </summary>
public class AuditRound8MigrationTests {
    // ------------------------------------------------------------------
    // Helper: build a minimal AutomaticRoutePlanningRequest from a
    // list of tasks. We don't need warehouses, items, or initial
    // inventory for the migration-only tests.
    // ------------------------------------------------------------------

    private static AutomaticRoutePlanningRequest BuildRequest(
        params (string rowId, string island, string item1, string item2,
                int inputQty, int outputQty)[] tasks) {
        var built = tasks
            .Select(t => new RouteBarterTask(t.rowId, t.island, new RoutePoint(0, 0),
                t.item1, t.inputQty, t.item2, t.outputQty))
            .ToList();
        var items = new Dictionary<string, RouteItem>(StringComparer.Ordinal);
        foreach (var t in tasks) {
            if (!items.ContainsKey(t.item1))
                items[t.item1] = new RouteItem(t.item1, t.item1, 1, 100);
            if (!items.ContainsKey(t.item2))
                items[t.item2] = new RouteItem(t.item2, t.item2, 2, 400);
        }
        return new AutomaticRoutePlanningRequest(
            built, items,
            new[] { new RouteWarehouse("Iliya", "Iliya", new RoutePoint(0, 0),
                new Dictionary<string, int>(StringComparer.Ordinal)) },
            extraLT: 0, totalLT: 100_000,
            new RouteSearchLimits(100_000, 1_000), "test-fp");
    }

    private static RoutePlan BuildPlan(params string[] barterStepRowIds) {
        var steps = new List<RouteStep>();
        foreach (var rowId in barterStepRowIds) {
            steps.Add(new BarterStep(rowId, "Iliya",
                new RouteItemQuantity("X", 1),
                new RouteItemQuantity("Y", 1),
                new RouteLoadSnapshot(0, 0, 0)));
        }
        return new RoutePlan(RoutePlanStatus.Optimal,
            new[] { new PlannedRoute(1, "Iliya", "Iliya", steps.ToArray(),
                distance: 0, initialLT: 0, currentLT: 0, peakLT: 0) },
            objective: null, diagnostics: Array.Empty<RouteDiagnostic>(), "saved-fp");
    }

    // ------------------------------------------------------------------
    // Identity-only migration: every saved BarterStep must map.
    // ------------------------------------------------------------------

    [Fact]
    public void IdentityMigration_DeletedBrRowId_Rejected() {
        // Saved plan references a RowId that no longer exists in the
        // current request's task list. Migration must refuse.
        var request = BuildRequest(("br-current", "Iliya", "X", "Y", 1, 1));
        var savedPlan = BuildPlan("br-deleted");
        var result = RoutePlanRestoreCompatibility.TryMigrateIdentityOnly(
            request, savedPlan);
        Assert.False(result.IsCompatible);
        Assert.NotNull(result.MismatchComponents);
        Assert.Contains(result.MismatchComponents!, s => s.Contains("br-deleted"));
    }

    [Fact]
    public void IdentityMigration_QuantityChange_Rejected() {
        // The saved plan declares Item1×2 → Item2×1 but the current
        // task is Item1×1 → Item2×1. The legacy tuple match (Island,
        // Item1, Item2) must NOT silently succeed when quantities
        // differ — the v1 path `continue`d past this case and let
        // invalid plans appear compatible.
        var request = BuildRequest(("br-current", "Iliya", "X", "Y", 1, 1));
        var savedPlan = new RoutePlan(RoutePlanStatus.Optimal,
            new[] { new PlannedRoute(1, "Iliya", "Iliya", new RouteStep[] {
                new BarterStep("Iliya:X:Y", "Iliya",
                    new RouteItemQuantity("X", 2),
                    new RouteItemQuantity("Y", 1),
                    new RouteLoadSnapshot(0, 0, 0)),
            }, distance: 0, initialLT: 0, currentLT: 0, peakLT: 0) },
            objective: null, diagnostics: Array.Empty<RouteDiagnostic>(), "saved-fp");
        var result = RoutePlanRestoreCompatibility.TryMigrateIdentityOnly(
            request, savedPlan);
        Assert.False(result.IsCompatible);
        Assert.NotNull(result.MismatchComponents);
        Assert.Contains(result.MismatchComponents!, s => s.Contains("no current-task match"));
    }

    [Fact]
    public void IdentityMigration_Item1Change_Rejected() {
        // Saved plan's legacy tuple says Item1 = "X". The current
        // task's Item1 is "X" too, but the Item2 is "Z" instead of
        // "Y". Migration must refuse the Item2 mismatch.
        var request = BuildRequest(("br-current", "Iliya", "X", "Z", 1, 1));
        var savedPlan = new RoutePlan(RoutePlanStatus.Optimal,
            new[] { new PlannedRoute(1, "Iliya", "Iliya", new RouteStep[] {
                new BarterStep("Iliya:X:Y", "Iliya",
                    new RouteItemQuantity("X", 1),
                    new RouteItemQuantity("Y", 1),
                    new RouteLoadSnapshot(0, 0, 0)),
            }, distance: 0, initialLT: 0, currentLT: 0, peakLT: 0) },
            objective: null, diagnostics: Array.Empty<RouteDiagnostic>(), "saved-fp");
        var result = RoutePlanRestoreCompatibility.TryMigrateIdentityOnly(
            request, savedPlan);
        Assert.False(result.IsCompatible);
        Assert.NotNull(result.MismatchComponents);
    }

    [Fact]
    public void IdentityMigration_AmbiguousTuple_Rejected() {
        // Two current tasks share the legacy (Island, Item1, Item2)
        // tuple. Migration must refuse to guess which one to map to.
        var request = BuildRequest(
            ("br-a", "Iliya", "X", "Y", 1, 1),
            ("br-b", "Iliya", "X", "Y", 1, 1));
        var savedPlan = new RoutePlan(RoutePlanStatus.Optimal,
            new[] { new PlannedRoute(1, "Iliya", "Iliya", new RouteStep[] {
                new BarterStep("Iliya:X:Y", "Iliya",
                    new RouteItemQuantity("X", 1),
                    new RouteItemQuantity("Y", 1),
                    new RouteLoadSnapshot(0, 0, 0)),
            }, distance: 0, initialLT: 0, currentLT: 0, peakLT: 0) },
            objective: null, diagnostics: Array.Empty<RouteDiagnostic>(), "saved-fp");
        var result = RoutePlanRestoreCompatibility.TryMigrateIdentityOnly(
            request, savedPlan);
        Assert.False(result.IsCompatible);
        Assert.NotNull(result.AmbiguousTuples);
        Assert.Contains(result.AmbiguousTuples!.Keys, k => k.Item2Id == "Y");
    }

    [Fact]
    public void IdentityMigration_UniqueLegacyTuple_MigratesSuccessfully() {
        // Single current task matches the legacy tuple. The migration
        // must succeed and produce a plan whose InputFingerprint
        // equals the new request's.
        var request = BuildRequest(("br-current", "Iliya", "X", "Y", 1, 1));
        var savedPlan = new RoutePlan(RoutePlanStatus.Optimal,
            new[] { new PlannedRoute(1, "Iliya", "Iliya", new RouteStep[] {
                new BarterStep("Iliya:X:Y", "Iliya",
                    new RouteItemQuantity("X", 1),
                    new RouteItemQuantity("Y", 1),
                    new RouteLoadSnapshot(0, 0, 0)),
            }, distance: 0, initialLT: 0, currentLT: 0, peakLT: 0) },
            objective: null, diagnostics: Array.Empty<RouteDiagnostic>(), "saved-fp");
        var result = RoutePlanRestoreCompatibility.TryMigrateIdentityOnly(
            request, savedPlan);
        Assert.True(result.IsCompatible);
        Assert.NotNull(result.MappedPlan);
        // Migrated fingerprint equals the current request's.
        Assert.Equal(RoutePlanFingerprint.Compute(request), result.MappedPlan!.InputFingerprint);
    }

    [Fact]
    public void IdentityMigration_MigratesSelectedBarterRowId() {
        // The selected pointer must follow the same mapping as the
        // saved BarterStep.RowId, so the cursor lands on the correct
        // task after migration.
        var request = BuildRequest(("br-current", "Iliya", "X", "Y", 1, 1));
        var savedPlan = new RoutePlan(RoutePlanStatus.Optimal,
            new[] { new PlannedRoute(1, "Iliya", "Iliya", new RouteStep[] {
                new BarterStep("Iliya:X:Y", "Iliya",
                    new RouteItemQuantity("X", 1),
                    new RouteItemQuantity("Y", 1),
                    new RouteLoadSnapshot(0, 0, 0)),
            }, distance: 0, initialLT: 0, currentLT: 0, peakLT: 0) },
            objective: null, diagnostics: Array.Empty<RouteDiagnostic>(), "saved-fp");
        var result = RoutePlanRestoreCompatibility.TryMigrateIdentityOnly(
            request, savedPlan, selectedBarterRowId: "Iliya:X:Y");
        Assert.True(result.IsCompatible);
        Assert.Equal("br-current", result.MigratedSelectedBarterRowId);
    }

    [Fact]
    public void IdentityMigration_DeletedSelectedBarterRowId_NotPropagated() {
        // If the saved SelectedBarterRowId no longer maps to any
        // current task, the migration must NOT invent a rowId for it.
        var request = BuildRequest(("br-current", "Iliya", "X", "Y", 1, 1));
        var savedPlan = new RoutePlan(RoutePlanStatus.Optimal,
            new[] { new PlannedRoute(1, "Iliya", "Iliya", new RouteStep[] {
                new BarterStep("Iliya:X:Y", "Iliya",
                    new RouteItemQuantity("X", 1),
                    new RouteItemQuantity("Y", 1),
                    new RouteLoadSnapshot(0, 0, 0)),
            }, distance: 0, initialLT: 0, currentLT: 0, peakLT: 0) },
            objective: null, diagnostics: Array.Empty<RouteDiagnostic>(), "saved-fp");
        var result = RoutePlanRestoreCompatibility.TryMigrateIdentityOnly(
            request, savedPlan, selectedBarterRowId: "Iliya:Deleted:Z");
        Assert.True(result.IsCompatible);
        // The selected pointer can't map; it stays null.
        Assert.Null(result.MigratedSelectedBarterRowId);
    }

    // ------------------------------------------------------------------
    // Barter.PlannerRowId round-trip via Newtonsoft (the actual JSON
    // library used by the production PlannerControl path).
    // ------------------------------------------------------------------

    [Fact]
    public void PlannerRowId_RoundTripsViaSystemTextJson() {
        // Audit round 8: this test pins the JSON data contract that
        // the PlannerRowId field name is preserved across a
        // parse → serialize → parse cycle.  The production save/load
        // path uses Newtonsoft.Json; System.Text.Json is used here
        // because the test assembly does not reference Newtonsoft.
        var id = "br-round-trip-aaaa";
        var json = $$"""
            {
              "PlannerRowId": "{{id}}",
              "IsLandName": "Iliya"
            }
            """;
        var parsed = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(json);
        Assert.NotNull(parsed);
        Assert.True(parsed!.ContainsKey("PlannerRowId"));
        Assert.Equal(id, parsed["PlannerRowId"].GetString());
    }

    [Fact]
    public void PlannerRowId_AuditRound3Clone_PreservesIdentityContract() {
        // The audit requires that reloading / RefreshDataGrid
        // preserves the persisted PlannerRowId.  Verify the data
        // contract by checking the JSON round-trip field name
        // and value preservation.
        const string id = "br-clone-test";
        const string json = "{\"PlannerRowId\":\"" + id + "\",\"IsLandName\":\"Iliya\"}";
        var firstRead = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(json);
        Assert.Equal(id, firstRead!["PlannerRowId"].GetString());
        // Simulate the refresh re-serialize round-trip.
        var reserialized = JsonSerializer.Serialize(firstRead);
        var secondRead = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(reserialized);
        Assert.Equal(id, secondRead!["PlannerRowId"].GetString());
    }
}