//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBarter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedComboBoxValueLV5 {
            get {
                return ((int)(this["SelectedComboBoxValueLV5"]));
            }
            set {
                this["SelectedComboBoxValueLV5"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedComboBoxValueLV6 {
            get {
                return ((int)(this["SelectedComboBoxValueLV6"]));
            }
            set {
                this["SelectedComboBoxValueLV6"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedComboBoxValueLV7 {
            get {
                return ((int)(this["SelectedComboBoxValueLV7"]));
            }
            set {
                this["SelectedComboBoxValueLV7"] = value;
            }
        }

        // AppLanguage: persisted active language selection for the
        // iBarter.Localization.LanguageService singleton (added Phase 1 of
        // the i18n refactor). Values: 0 = English, 1 = TraditionalChinese.
        // The SettingsSingleFileGenerator is regenerating this file as the
        // .settings side gains keys; this stub is hand-maintained for now.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AppLanguage {
            get {
                return ((int)(this["AppLanguage"]));
            }
            set {
                this["AppLanguage"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CustomRouteSearchMinutes {
            get {
                return ((int)(this["CustomRouteSearchMinutes"]));
            }
            set {
                this["CustomRouteSearchMinutes"] = value;
            }
        }
    }
}
